- 
  name: "Run Exakat Enterprise"
  uses: exakat/exakat-enterprise@v1
  with: 
    format: sarif
    output: results.sarif
    project-token: "${{ secrets.EXAKAT_TOKEN }}"
- 
  name: "Upload SARIF results file"
  uses: github/codeql-action/upload-sarif@v1
  with: 
    sarif_file: results.sarif
